### ISSUE TITLE
why out_channels=4 * self.hidden_dim?  

### ISSUE THREAD

**Issue by cuixianheng** [ndrplz/ConvLSTM_pytorch#23]
why out_channels=4 * self.hidden_dim?

**Comment by Berndinio** [comment]
Because they split it afterwards in 

cc_i, cc_f, cc_o, cc_g = torch.split(combined_conv, self.hidden_dim, dim=1)

f, g, o and g all have the same convolution operation (but with independent weights). 
If you have a hidden.channel + x.channel = 4 input

**Comment by ndrplz** [comment]
Thanks @Berndinio 

Also [this](https://github.com/ndrplz/ConvLSTM_pytorch/issues/8#issuecomment-501313442) answer might help
