### ISSUE TITLE
split_size_or_sections

### ISSUE THREAD

**Issue by geoyee** [ndrplz/ConvLSTM_pytorch#25]
Sorry, my English is not very good. Why split_size_or_sections is  self.hidden_dim? There are only 4 variables to receive the result, I think self.hidden_dim should be changed to 4

44     cc_i, cc_f, cc_o, cc_g = torch.split(combined_conv, self.hidden_dim, dim=1)

**Comment by tanguihong** [comment]
Author is right.becacuse the second parameter(split_size_or_sections) of  torch.split means the size of each chunks splited from the original tensor.
